### PR TITLE
Cleanups and save button

### PR DESCRIPTION
**Pull request by pinussilvestrus**
This includes some general housekeeping + adding a save icon inside the editor.

Kapture 2021-05-12 at 13 51 14

Rationale:

We received some feedback in the past that saving diagram changes is hard to discover (cf. https://github.com/bpmn-io/vs-code-bpmn-io/issues/88, https://github.com/bpmn-io/vs-code-bpmn-io/issues/96#issuecomment-838829699). We have some limitations to fully support the "natural" save behavior inside VS Code editors (cf. https://github.com/bpmn-io/vs-code-bpmn-io/issues/88#issuecomment-821065672, https://github.com/bpmn-io/vs-code-bpmn-io/issues/48).

I think adding a save icon to the editor itself should make it at least easier to discover that you actually _can save_. It's still possible to do it via keyboard shortcut + autosave (if enabled) though. I'm using the [official icon font ](https://github.com/microsoft/vscode-codicons) here.

Let me hear what you think 👍

### CODE REVIEW

**Review by andreasgeier — APPROVED** [review]
As far as I understood, it is not possible to bind the action to the save entry in the app menu, which would be the ideal way.

✅ &nbsp; Therefore, the proposal seems to be a valid fallback.

However, you could consider the following enhancements:

- show it only on dirty state to provide an indication when save is needed
- add text to the icon to make the action more understandable, and to promote the keyboard shortcut – e.g. `[icon] Save (cmd+s)`
- move it to the bottom right next to the BPMN logo to not use the third corner and keep the canvas organized

**Comment by nikku** [comment]
@pinussilvestrus Can you verify the following? 

> As far as I understood, it is not possible to bind the action to the save entry in the app menu, which would be the ideal way.

From my point of view we should not add the save button without critical need. It does not fit into the way VS-Code editors _work_ and thus should be avoided. Putting it in places where usual icons reside, i.e. here could be a way to remedy the situation. Maybe we could even show a dirty state indicator there?

image

If your assessment is that a proper solution (cf. https://github.com/bpmn-io/vs-code-bpmn-io/pull/97#pullrequestreview-657943222, tab dirty state indicator, ...) won't work for now and you believe this is a critical issue I'd still be fine merging this as a _temporary hack_.

**Comment by pinussilvestrus** [comment]
I could also think about many alternatives how to better indicate the need for savings. As you both said, most of them are currently not possible, because the extension is not a native editor. Building that is not an easy task.

Adding the simple button should act as a hacky workaround for now to (as I hope) reduce the opened issues asking how to save changes. I'd also okay with not merging it if you have strong doubts 🙂 

> last, you could replace the save icon with the progress icon in progress state instead of showing it next to

I added this one as a small improvement.

Kapture 2021-05-17 at 16 09 16

**Review by nikku — APPROVED** [review]
Let's accept that workarounds exist. Maybe we can improve the integration into VSCode some day in the future. Looking forward for it being a real editor, one day, maybe.

**Pull request merged**
