### PR TITLE
ci: publish automatically

### LINKED ISSUE #121: Automate updates and publishing
### Is your feature request related to a problem? Please describe.

We use bpmn-js@12 in this extension while current major is 13. Even if we update it, [release has to be done manually](https://github.com/bpmn-io/vs-code-bpmn-io/blob/master/docs/RELEASING.md). 
Let's automate this so that:
* users can benefit from the latest version
* developers don't need to do boring stuff

### Describe the solution you'd like

* [x] Automate deps updates with renovate
* [ ] Publish releases with a GH Action
* [ ] (optional) Integrate [release-please](https://github.com/googleapis/release-please) or similar tool

### PR DESCRIPTION
**Pull request by barmac**
Closes #121

We need to either update the token or give me permissions to publish the extension before we merge this.

### CODE REVIEW

**Comment by barmac** [comment]
This is now ready for review @philippfromme @marstamm.

**Comment by philippfromme** [comment]
Looks good. How do we go about testing this? Merge and see if the next release works?

**Comment by barmac** [comment]
That's exactly how we'd test this.

**Comment by barmac** [comment]
Too bad `vsce` doesn't have dry-run mode :(

**Comment by barmac** [comment]
This is happening via https://github.com/bpmn-io/vs-code-bpmn-io/pull/137

**Pull request merged**
