### PR TITLE
Bump bpmn-js + support collapsed sub processes

### LINKED ISSUE #105: Upgrade to bpmn-js@9
__What should we do?__

Upgrade `bpmn-js` dependency to [latest version](https://github.com/bpmn-io/bpmn-js/blob/develop/CHANGELOG.md#900-alpha2).

__Why should we do it?__

Include the latest stuff.

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Closes #105 

Kapture 2022-04-08 at 14 34 22

### CODE REVIEW

**Comment by barmac** [comment]
I installed the plugin, pressed `F5`, and this happened:

https://user-images.githubusercontent.com/28307541/162464083-4b7d329b-91e6-4c12-b4f2-3bf072d65c26.mov

**Comment by pinussilvestrus** [comment]
Weird, as I didn't update the styles. Which VSCode version do you use?

**Comment by barmac** [comment]
Version: 1.66.1
Commit: 8dfae7a5cd50421d10cd99cb873990460525a898
Date: 2022-04-06T14:49:47.400Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin x64 21.3.0

**Comment by pinussilvestrus** [comment]
I have kind an older OS version (Darwin arm64 20.6.0), but I doubt that this should make a difference. Let's check some other things

* does this styling also appear on `master` for you?
* which theme do you use? Maybe this affects the styling of web views?
* which other plugins do you have installed?
* is there anything in the developer tool logs (Open with Help > Toggle Developer Tools)?

**Comment by barmac** [comment]
OK it was my fault. I should have run `npm run compile` before "F5".

**Comment by barmac** [comment]
There was one error in the developer tools after the compilation: 
image

**Comment by pinussilvestrus** [comment]
> OK it was my fault. I should have run `npm run compile` before "F5".

Mh maybe we should[ update the `launch` script](https://github.com/bpmn-io/vs-code-bpmn-io/blob/master/.vscode/launch.json#L15) to also compile the styles, not only ts.

**Review by barmac — APPROVED** [review]

**Comment by pinussilvestrus** [comment]
> There was one error in the developer tools after the compilation: image

Thanks for mentioning that? This was actually broken for a while (displaying the editor icon on the file editor) 😅

Fixed via d233c121084c49d83d25c8a8b91f0271714b8324

image

image

image
 
 
image

**Pull request merged**
